url: https://xfair.io
title: xFair | February 25, 2020
description: MIT's largest career fair & tech expo. Feb 25, 2020 @ MIT Media Lab.

favicon-path: "assets/xfair_favicon.png"
logo-path-png: "assets/xfair_logo.png"

sponsor-info-path: "https://drive.google.com/file/d/1J59RQV85-dzOP01SAMtMVh7Jq7qnqRd-/view?usp=sharing"
company-lab-app-path: "https://apply.xfair.io"
smart-casual-link: "https://en.wikipedia.org/wiki/Smart_casual"
fb-link: "https://www.facebook.com/MITxFair/"
twitter-link: "https://twitter.com/MITxFair"
tbp: "http://web.mit.edu/tbp/www/"
techx: "https://techx.io"

nav-links:
  - title: Employers
    url: "#employers"
  - title: Research Groups
    url: "#research-groups"
  - title: Students
    url: "#students"
  - title: Student Exhibitors
    url: "#student-exhibitors"
  - title: FAQ
    url: "#faq"

sass:
  style: compressed
