url: https://xfair.io
title: xFair | March 8, 2021
description: MIT's largest career fair & tech expo. March 8, 2021.

favicon-path: "assets/xfair-logo-favicon.png"
logo-path-png: "assets/xfair_logo.png"

sponsor-info-path: "https://drive.google.com/file/d/1OVF2qkOEVgsnP-JsRCWcmGTw4KUVprGh/view?usp=sharing"
resume-drop-path: "https://drop.xfair.io"
company-lab-app-path: "https://apply.xfair.io"
smart-casual-link: "https://en.wikipedia.org/wiki/Smart_casual"
fb-link: "https://www.facebook.com/MITxFair/"
twitter-link: "https://twitter.com/MITxFair"
tbp: "http://web.mit.edu/tbp/www/"
techx: "https://techx.io"

nav-links:
  - title: Employers
    url: "#employers"
  - title: Research Groups
    url: "#research-groups"
  - title: Students
    url: "#students"
  - title: ProjXpo
    url: "#student-exhibitors"
  - title: FAQ
    url: "#faq"

sass:
  style: compressed
